// <auto-generated />
using System;
using IBSCardManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IBSCardManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260723140859_InitialEnterpriseDatabase")]
    partial class InitialEnterpriseDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IBSCardManager.Entities.Brand", b =>
                {
                    b.Property<Guid>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("BrandId");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            BrandId = new Guid("22222222-2222-2222-2222-222222222222"),
                            BrandName = "Topps",
                            IsActive = true
                        },
                        new
                        {
                            BrandId = new Guid("33333333-3333-3333-3333-333333333333"),
                            BrandName = "Bowman",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("IBSCardManager.Entities.Card", b =>
                {
                    b.Property<Guid>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AutographGrade")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BackImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("BestOfferEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("CardNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("CatalogConfidence")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CatalogRecordId")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CatalogSource")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("CatalogSourceRecordId")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("CatalogUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CatalogVersion")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CertNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ChecklistItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EbayCategoryId")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("EbayCondition")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("EbayDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EbaySku")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("EbayTitle")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("FrontImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Grade")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GradeIssuer")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImageSourcePreference")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsAutograph")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRefractor")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRelic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRookie")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUserCreated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("ListingFormat")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal?>("ListingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ListingStatus")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("MyCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MyNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MyValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PackageHeightIn")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PackageLengthIn")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PackageWeightOz")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PackageWidthIn")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("PaymentPolicyName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("PsaEstimate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid?>("ReplacedByCatalogRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReturnPolicyName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Serial")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Set")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ShippingPolicyName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("StockImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("StorageBin")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StorageBox")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StorageRow")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Team")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Variety")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("CardId");

                    b.HasIndex("CardNumber");

                    b.HasIndex("CatalogRecordId");

                    b.HasIndex("CertNumber");

                    b.HasIndex("ChecklistItemId");

                    b.HasIndex("Set");

                    b.HasIndex("Subject");

                    b.HasIndex("Team");

                    b.HasIndex("CatalogVersion", "IsVerified", "IsDeprecated");

                    b.HasIndex("ProductId", "ChecklistItemId", "CatalogSourceRecordId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("IBSCardManager.Entities.ChecklistImportHistory", b =>
                {
                    b.Property<Guid>("ChecklistImportHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImportProfile")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("ImportedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenseUsageNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RetrievedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RowsImported")
                        .HasColumnType("int");

                    b.Property<int>("RowsRead")
                        .HasColumnType("int");

                    b.Property<int>("RowsUpdated")
                        .HasColumnType("int");

                    b.Property<string>("SourceFile")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("SourceProductIdentifier")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SourceVersion")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("ChecklistImportHistoryId");

                    b.HasIndex("ProductId", "ImportedUtc");

                    b.ToTable("ChecklistImportHistories");
                });

            modelBuilder.Entity("IBSCardManager.Entities.ChecklistItem", b =>
                {
                    b.Property<Guid>("ChecklistItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalSubjects")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AdditionalTeams")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CachedThumbnailPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("CatalogConfidence")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CatalogRecordId")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CatalogSource")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("CatalogSourceRecordId")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("CatalogUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CatalogVersion")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ImportProfile")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsAutograph")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRefractor")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRelic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRookie")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUserCreated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Parallel")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PrintRun")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReferenceImageDateLocatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReferenceImageHash")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ReferenceImageSource")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ReferenceImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ReferenceImageUsageStatus")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ReferenceImageVerificationStatus")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ReferencePageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("ReplacedByCatalogRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SourceCardIdentifier")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("SourceDateImportedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SourceDateRetrievedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceFile")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SourceLicenseUsageNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SourceName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int?>("SourceOriginalRowNumber")
                        .HasColumnType("int");

                    b.Property<string>("SourceProductIdentifier")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SourceRawValuesJson")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("SourceType")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SourceVerificationStatus")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("SourceVersion")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("StockBackImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("StockImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Subset")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Team")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Variation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ChecklistItemId");

                    b.HasIndex("CatalogRecordId");

                    b.HasIndex("CatalogVersion", "IsVerified", "IsDeprecated");

                    b.HasIndex("ProductId", "CardNumber", "Subject");

                    b.HasIndex("ProductId", "CardNumber", "Parallel", "Variation");

                    b.ToTable("ChecklistItems");
                });

            modelBuilder.Entity("IBSCardManager.Entities.CollectionSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicationVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("GradedValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HighConfidenceValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ListedValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LowConfidenceValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RawValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RealizedProfit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("SnapshotDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoldValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalCards")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCostBasis")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalEstimatedValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("int");

                    b.Property<int>("UniqueCards")
                        .HasColumnType("int");

                    b.Property<decimal>("UnrealizedGain")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnrealizedLoss")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotDate");

                    b.ToTable("CollectionSnapshots");
                });

            modelBuilder.Entity("IBSCardManager.Entities.DecisionHistoryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AlternativeOptionsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationVersion")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("CatalogVersion")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ConfidenceScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DecisionStatus")
                        .HasColumnType("int");

                    b.Property<int>("DecisionType")
                        .HasColumnType("int");

                    b.Property<int>("EvidenceCount")
                        .HasColumnType("int");

                    b.Property<string>("ExplanationSummary")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("MissingDataSummary")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid?>("PreviousDecisionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PromptVersion")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("RuleVersion")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("SelectedOption")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("SubjectStableId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("SubjectType")
                        .HasColumnType("int");

                    b.Property<string>("UserAction")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectType", "SubjectStableId", "CreatedAt");

                    b.ToTable("DecisionHistoryRecords");
                });

            modelBuilder.Entity("IBSCardManager.Entities.InventoryAnalyticsSummary", b =>
                {
                    b.Property<Guid>("InventoryCardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CostBasis")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CurrentEstimatedValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DemandScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("GradingScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("HoldScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("LastCalculatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LiquidityScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PriceConfidence")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("PriceFreshness")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("ROI")
                        .HasColumnType("decimal(9,4)");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("RecommendationReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("SellScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("UnrealizedGainLoss")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("InventoryCardId");

                    b.HasIndex("LastCalculatedAt");

                    b.ToTable("InventoryAnalyticsSummaries");
                });

            modelBuilder.Entity("IBSCardManager.Entities.KnowledgeAuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AfterValuesJson")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ApplicationVersion")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("BeforeValuesJson")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("CatalogVersion")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("OperationResult")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OperationType")
                        .HasColumnType("int");

                    b.Property<string>("RuleVersion")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("SubjectStableId")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("KnowledgeAuditRecords");
                });

            modelBuilder.Entity("IBSCardManager.Entities.KnowledgeEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ConfidenceContribution")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EvidenceSummary")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EvidenceType")
                        .HasColumnType("int");

                    b.Property<bool>("IsContradicting")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSupporting")
                        .HasColumnType("bit");

                    b.Property<Guid>("KnowledgeRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("NormalizedValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ObservedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RawValue")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("RuleVersion")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("SourceRecordId")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("SourceType")
                        .HasColumnType("int");

                    b.Property<string>("SourceUri")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeRecordId");

                    b.ToTable("KnowledgeEvidence");
                });

            modelBuilder.Entity("IBSCardManager.Entities.KnowledgeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CatalogConfirmationCount")
                        .HasColumnType("int");

                    b.Property<decimal>("ConfidenceScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FirstObservedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ImageMatchConfirmationCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("bit");

                    b.Property<int>("KnowledgeType")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastObservedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastVerifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MarketplaceConfirmationCount")
                        .HasColumnType("int");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("NormalizedValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("ReplacedByKnowledgeRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RuleVersion")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("SourceCount")
                        .HasColumnType("int");

                    b.Property<string>("StableId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("StatementKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("StatementValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SubjectStableId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("SubjectType")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserConfirmationCount")
                        .HasColumnType("int");

                    b.Property<int>("UserCorrectionCount")
                        .HasColumnType("int");

                    b.Property<int>("VerificationLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConfidenceScore");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("KnowledgeType");

                    b.HasIndex("StableId")
                        .IsUnique();

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("VerificationLevel");

                    b.HasIndex("SubjectType", "SubjectStableId");

                    b.ToTable("KnowledgeRecords");
                });

            modelBuilder.Entity("IBSCardManager.Entities.KnowledgeReviewItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<Guid?>("KnowledgeRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RuleVersion")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SubjectStableId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("SubjectType")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.ToTable("KnowledgeReviewItems");
                });

            modelBuilder.Entity("IBSCardManager.Entities.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("CatalogConfidence")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CatalogRecordId")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CatalogSource")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("CatalogSourceRecordId")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("CatalogUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CatalogVersion")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ChecklistAvailabilityStatus")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime?>("ChecklistLastImportedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUserCreated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("LastChecklistImportSource")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReplacedByCatalogRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("BrandId");

                    b.HasIndex("CatalogRecordId");

                    b.HasIndex("SportId");

                    b.HasIndex("CatalogSourceRecordId", "CatalogVersion", "IsVerified");

                    b.HasIndex("Year", "BrandId", "ProductName")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("IBSCardManager.Entities.RecommendationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Accepted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("Dismissed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InventoryCardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Reasons")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecommendationType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("RequiredActions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Risks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RuleVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("SnoozedUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("UserNotes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InventoryCardId", "RecommendationType", "GeneratedAt");

                    b.ToTable("RecommendationRecords");
                });

            modelBuilder.Entity("IBSCardManager.Entities.Sport", b =>
                {
                    b.Property<Guid>("SportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("SportName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SportId");

                    b.ToTable("Sports");

                    b.HasData(
                        new
                        {
                            SportId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SportName = "Baseball"
                        });
                });

            modelBuilder.Entity("IBSCardManager.Entities.UserAnalyticsPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CollectionGoal")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal>("MinimumCashFlowTarget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("NotifyDuplicateInventory")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyGradingOpportunity")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyListingSold")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyLowConfidenceIdentification")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyMissingCostBasis")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyPriceDecrease")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyPriceIncrease")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyReadyToList")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyStaleValuation")
                        .HasColumnType("bit");

                    b.Property<string>("ProfileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileName")
                        .IsUnique();

                    b.ToTable("UserAnalyticsPreferences");
                });

            modelBuilder.Entity("IBSCardManager.Entities.UserCorrection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AppliedToCurrentRecord")
                        .HasColumnType("bit");

                    b.Property<string>("CorrectedValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("CorrectionType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EligibleForLearning")
                        .HasColumnType("bit");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("LearningStatus")
                        .HasColumnType("int");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("OriginalValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RuleVersion")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("SubjectStableId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("SubjectType")
                        .HasColumnType("int");

                    b.Property<string>("UserNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("LearningStatus");

                    b.HasIndex("SubjectType", "SubjectStableId");

                    b.ToTable("UserCorrections");
                });

            modelBuilder.Entity("IBSCardManager.Entities.WebSearchResult", b =>
                {
                    b.Property<Guid>("WebSearchResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateRetrievedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("MetadataJson")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("PageSource")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SearchQuery")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SearchScope")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("UserConfirmed")
                        .HasColumnType("bit");

                    b.HasKey("WebSearchResultId");

                    b.HasIndex("ProductId", "SearchScope", "DateRetrievedUtc");

                    b.ToTable("WebSearchResults");
                });

            modelBuilder.Entity("IBSCardManager.Entities.Card", b =>
                {
                    b.HasOne("IBSCardManager.Entities.ChecklistItem", "ChecklistItem")
                        .WithMany()
                        .HasForeignKey("ChecklistItemId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("IBSCardManager.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ChecklistItem");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("IBSCardManager.Entities.ChecklistImportHistory", b =>
                {
                    b.HasOne("IBSCardManager.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("IBSCardManager.Entities.ChecklistItem", b =>
                {
                    b.HasOne("IBSCardManager.Entities.Product", "Product")
                        .WithMany("ChecklistItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("IBSCardManager.Entities.InventoryAnalyticsSummary", b =>
                {
                    b.HasOne("IBSCardManager.Entities.Card", "InventoryCard")
                        .WithMany()
                        .HasForeignKey("InventoryCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryCard");
                });

            modelBuilder.Entity("IBSCardManager.Entities.KnowledgeEvidence", b =>
                {
                    b.HasOne("IBSCardManager.Entities.KnowledgeRecord", "KnowledgeRecord")
                        .WithMany("Evidence")
                        .HasForeignKey("KnowledgeRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KnowledgeRecord");
                });

            modelBuilder.Entity("IBSCardManager.Entities.Product", b =>
                {
                    b.HasOne("IBSCardManager.Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IBSCardManager.Entities.Sport", "Sport")
                        .WithMany("Products")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("IBSCardManager.Entities.RecommendationRecord", b =>
                {
                    b.HasOne("IBSCardManager.Entities.Card", "InventoryCard")
                        .WithMany()
                        .HasForeignKey("InventoryCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryCard");
                });

            modelBuilder.Entity("IBSCardManager.Entities.WebSearchResult", b =>
                {
                    b.HasOne("IBSCardManager.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Product");
                });

            modelBuilder.Entity("IBSCardManager.Entities.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("IBSCardManager.Entities.KnowledgeRecord", b =>
                {
                    b.Navigation("Evidence");
                });

            modelBuilder.Entity("IBSCardManager.Entities.Product", b =>
                {
                    b.Navigation("ChecklistItems");
                });

            modelBuilder.Entity("IBSCardManager.Entities.Sport", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
